name: Deploy to github.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install, lint, build
        run: |
          bun install
          bun run lint:fix
          bun run build
        env:
          BASE_URL: "/react-vnc"

      - name: Deploy to github.io
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
