name: Check for lint/build errors
on:
  pull_request:
    branches:
      - "**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install and lint
        run: |
          bun install
          bun run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install and build
        run: |
          bun install
          bun run build
          bun run build:lib
